name: CI/CI

on: 
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build Module
        shell: pwsh
        run: ./build.ps1 -Task ModuleBuild

      - name: Test Module
        shell: pwsh
        run: Invoke-Build -Task Test

      - name: Publish Module
        if: ${{ github.event_name == 'push' }}
        shell: pwsh
        run: Invoke-Build -Task Publish